// List of supported languages from Wikipedia at https://meta.wikimedia.org/wiki/List_of_Wikipedias_by_country
export const languages = [
  { code: 'en', language: 'English' },
  { code: 'ceb', language: 'Cebuano' },
  { code: 'sv', language: 'Swedish' },
  { code: 'de', language: 'German' },
  { code: 'fr', language: 'French' },
  { code: 'nl', language: 'Dutch' },
  { code: 'ru', language: 'Russian' },
  { code: 'it', language: 'Italian' },
  { code: 'es', language: 'Spanish' },
  { code: 'pl', language: 'Polish' },
  { code: 'war', language: 'Waray-Waray' },
  { code: 'vi', language: 'Vietnamese' },
  { code: 'ja', language: 'Japanese' },
  { code: 'arz', language: 'Egyptian Arabic' },
  { code: 'zh', language: 'Chinese' },
  { code: 'ar', language: 'Arabic' },
  { code: 'uk', language: 'Ukrainian' },
  { code: 'pt', language: 'Portuguese' },
  { code: 'fa', language: 'Persian' },
  { code: 'ca', language: 'Catalan' },
  { code: 'sr', language: 'Serbian' },
  { code: 'id', language: 'Indonesian' },
  { code: 'no', language: 'Norwegian (Bokmål)' },
  { code: 'ko', language: 'Korean' },
  { code: 'fi', language: 'Finnish' },
  { code: 'hu', language: 'Hungarian' },
  { code: 'cs', language: 'Czech' },
  { code: 'sh', language: 'Serbo-Croatian' },
  { code: 'zh-min-nan', language: 'Min Nan' },
  { code: 'ro', language: 'Romanian' },
  { code: 'tr', language: 'Turkish' },
  { code: 'eu', language: 'Basque' },
  { code: 'ce', language: 'Chechen' },
  { code: 'ms', language: 'Malay' },
  { code: 'eo', language: 'Esperanto' },
  { code: 'he', language: 'Hebrew' },
  { code: 'hy', language: 'Armenian' },
  { code: 'bg', language: 'Bulgarian' },
  { code: 'da', language: 'Danish' },
  { code: 'azb', language: 'South Azerbaijani' },
  { code: 'tt', language: 'Tatar' },
  { code: 'sk', language: 'Slovak' },
  { code: 'kk', language: 'Kazakh' },
  { code: 'min', language: 'Minangkabau' },
  { code: 'hr', language: 'Croatian' },
  { code: 'et', language: 'Estonian' },
  { code: 'lt', language: 'Lithuanian' },
  { code: 'be', language: 'Belarusian' },
  { code: 'el', language: 'Greek' },
  { code: 'simple', language: 'Simple English' },
  { code: 'az', language: 'Azerbaijani' },
  { code: 'sl', language: 'Slovenian' },
  { code: 'gl', language: 'Galician' },
  { code: 'ur', language: 'Urdu' },
  { code: 'nn', language: 'Norwegian (Nynorsk)' },
  { code: 'ka', language: 'Georgian' },
  { code: 'hi', language: 'Hindi' },
  { code: 'th', language: 'Thai' },
  { code: 'uz', language: 'Uzbek' },
  { code: 'la', language: 'Latin' },
  { code: 'ta', language: 'Tamil' },
  { code: 'cy', language: 'Welsh' },
  { code: 'vo', language: 'Volapük' },
  { code: 'mk', language: 'Macedonian' },
  { code: 'ast', language: 'Asturian' },
  { code: 'zh-yue', language: 'Cantonese' },
  { code: 'lv', language: 'Latvian' },
  { code: 'tg', language: 'Tajik' },
  { code: 'bn', language: 'Bengali' },
  { code: 'af', language: 'Afrikaans' },
  { code: 'mg', language: 'Malagasy' },
  { code: 'oc', language: 'Occitan' },
  { code: 'bs', language: 'Bosnian' },
  { code: 'sq', language: 'Albanian' },
  { code: 'nds', language: 'Low Saxon' },
  { code: 'ky', language: 'Kirghiz' },
  { code: 'new', language: 'Newar' },
  { code: 'be-tarask', language: 'Belarusian (Taraškievica)' },
  { code: 'ml', language: 'Malayalam' },
  { code: 'te', language: 'Telugu' },
  { code: 'br', language: 'Breton' },
  { code: 'vec', language: 'Venetian' },
  { code: 'mr', language: 'Marathi' },
  { code: 'pms', language: 'Piedmontese' },
  { code: 'tl', language: 'Tagalog' },
  { code: 'jv', language: 'Javanese' },
  { code: 'su', language: 'Sundanese' },
  { code: 'ht', language: 'Haitian' },
  { code: 'sw', language: 'Swahili' },
  { code: 'lb', language: 'Luxembourgish' },
  { code: 'pnb', language: 'Western Punjabi' },
  { code: 'ba', language: 'Bashkir' },
  { code: 'ga', language: 'Irish' },
  { code: 'my', language: 'Burmese' },
  { code: 'szl', language: 'Silesian' },
  { code: 'is', language: 'Icelandic' },
  { code: 'fy', language: 'West Frisian' },
  { code: 'cv', language: 'Chuvash' },
  { code: 'lmo', language: 'Lombard' },
  { code: 'sco', language: 'Scots' },
  { code: 'wuu', language: 'Wu' },
  { code: 'diq', language: 'Zazaki' },
  { code: 'an', language: 'Aragonese' },
  { code: 'pa', language: 'Punjabi' },
  { code: 'ku', language: 'Kurdish' },
  { code: 'yo', language: 'Yoruba' },
  { code: 'ne', language: 'Nepali' },
  { code: 'bar', language: 'Bavarian' },
  { code: 'io', language: 'Ido' },
  { code: 'gu', language: 'Gujarati' },
  { code: 'ckb', language: 'Sorani' },
  { code: 'als', language: 'Alemannic' },
  { code: 'kn', language: 'Kannada' },
  { code: 'scn', language: 'Sicilian' },
  { code: 'bpy', language: 'Bishnupriya Manipuri' },
  { code: 'ia', language: 'Interlingua' },
  { code: 'qu', language: 'Quechua' },
  { code: 'mn', language: 'Mongolian' },
  { code: 'bat-smg', language: 'Samogitian' },
  { code: 'si', language: 'Sinhalese' },
  { code: 'nv', language: 'Navajo' },
  { code: 'or', language: 'Oriya' },
  { code: 'cdo', language: 'Min Dong' },
  { code: 'ilo', language: 'Ilokano' },
  { code: 'gd', language: 'Scottish Gaelic' },
  { code: 'xmf', language: 'Mingrelian' },
  { code: 'yi', language: 'Yiddish' },
  { code: 'am', language: 'Amharic' },
  { code: 'nap', language: 'Neapolitan' },
  { code: 'bug', language: 'Buginese' },
  { code: 'wa', language: 'Walloon' },
  { code: 'sd', language: 'Sindhi' },
  { code: 'hsb', language: 'Upper Sorbian' },
  { code: 'mai', language: 'Maithili' },
  { code: 'fo', language: 'Faroese' },
  { code: 'map-bms', language: 'Banyumasan' },
  { code: 'mzn', language: 'Mazandarani' },
  { code: 'li', language: 'Limburgish' },
  { code: 'sah', language: 'Sakha' },
  { code: 'os', language: 'Ossetian' },
  { code: 'eml', language: 'Emilian-Romagnol' },
  { code: 'frr', language: 'North Frisian' },
  { code: 'ps', language: 'Pashto' },
  { code: 'sa', language: 'Sanskrit' },
  { code: 'avk', language: 'Kotava' },
  { code: 'gor', language: 'Gorontalo' },
  { code: 'bcl', language: 'Central Bicolano' },
  { code: 'zh-classical', language: 'Classical Chinese' },
  { code: 'ace', language: 'Acehnese' },
  { code: 'mrj', language: 'Hill Mari' },
  { code: 'mhr', language: 'Meadow Mari' },
  { code: 'hif', language: 'Fiji Hindi' },
  { code: 'hak', language: 'Hakka' },
  { code: 'roa-tara', language: 'Tarantino' },
  { code: 'pam', language: 'Kapampangan' },
  { code: 'hyw', language: 'Western Armenian' },
  { code: 'km', language: 'Khmer' },
  { code: 'nso', language: 'Northern Sotho' },
  { code: 'crh', language: 'Crimean Tatar' },
  { code: 'rue', language: 'Rusyn' },
  { code: 'shn', language: 'Shan' },
  { code: 'se', language: 'Northern Sami' },
  { code: 'as', language: 'Assamese' },
  { code: 'bh', language: 'Bhojpuri' },
  { code: 'vls', language: 'West Flemish' },
  { code: 'mi', language: 'Maori' },
  { code: 'nds-nl', language: 'Dutch Low Saxon' },
  { code: 'nah', language: 'Nahuatl' },
  { code: 'sc', language: 'Sardinian' },
  { code: 'ha', language: 'Hausa' },
  { code: 'vep', language: 'Vepsian' },
  { code: 'gan', language: 'Gan' },
  { code: 'sn', language: 'Shona' },
  { code: 'myv', language: 'Erzya' },
  { code: 'ab', language: 'Abkhazian' },
  { code: 'glk', language: 'Gilaki' },
  { code: 'bo', language: 'Tibetan' },
  { code: 'so', language: 'Somali' },
  { code: 'co', language: 'Corsican' },
  { code: 'tk', language: 'Turkmen' },
  { code: 'kab', language: 'Kabyle' },
  { code: 'fiu-vro', language: 'Võro' },
  { code: 'sat', language: 'Santali' },
  { code: 'zu', language: 'Zulu' },
  { code: 'csb', language: 'Kashubian' },
  { code: 'kv', language: 'Komi' },
  { code: 'ban', language: 'Balinese' },
  { code: 'ie', language: 'Interlingue' },
  { code: 'pcd', language: 'Picard' },
  { code: 'gv', language: 'Manx' },
  { code: 'udm', language: 'Udmurt' },
  { code: 'ay', language: 'Aymara' },
  { code: 'ug', language: 'Uyghur' },
  { code: 'zea', language: 'Zeelandic' },
  { code: 'nrm', language: 'Norman' },
  { code: 'lij', language: 'Ligurian' },
  { code: 'kw', language: 'Cornish' },
  { code: 'frp', language: 'Franco-Provençal' },
  { code: 'lez', language: 'Lezgian' },
  { code: 'gn', language: 'Guarani' },
  { code: 'lfn', language: 'Lingua Franca Nova' },
  { code: 'stq', language: 'Saterland Frisian' },
  { code: 'mwl', language: 'Mirandese' },
  { code: 'gom', language: 'Goan Konkani' },
  { code: 'rm', language: 'Romansh' },
  { code: 'mt', language: 'Maltese' },
  { code: 'lo', language: 'Lao' },
  { code: 'lad', language: 'Ladino' },
  { code: 'olo', language: 'Livvi-Karelian' },
  { code: 'koi', language: 'Komi-Permyak' },
  { code: 'fur', language: 'Friulian' },
  { code: 'bjn', language: 'Banjar' },
  { code: 'ang', language: 'Anglo-Saxon' },
  { code: 'dty', language: 'Doteli' },
  { code: 'dsb', language: 'Lower Sorbian' },
  { code: 'ext', language: 'Extremaduran' },
  { code: 'ln', language: 'Lingala' },
  { code: 'cbk-zam', language: 'Zamboanga Chavacano' },
  { code: 'tyv', language: 'Tuvan' },
  { code: 'ary', language: 'Moroccan Arabic' },
  { code: 'dv', language: 'Divehi' },
  { code: 'ksh', language: 'Ripuarian' },
  { code: 'gag', language: 'Gagauz' },
  { code: 'pfl', language: 'Palatinate German' },
  { code: 'pi', language: 'Pali' },
  { code: 'pag', language: 'Pangasinan' },
  { code: 'av', language: 'Avar' },
  { code: 'awa', language: 'Awadhi' },
  { code: 'haw', language: 'Hawaiian' },
  { code: 'bxr', language: 'Buryat' },
  { code: 'xal', language: 'Kalmyk' },
  { code: 'ig', language: 'Igbo' },
  { code: 'krc', language: 'Karachay-Balkar' },
  { code: 'pap', language: 'Papiamentu' },
  { code: 'za', language: 'Zhuang' },
  { code: 'rw', language: 'Kinyarwanda' },
  { code: 'pdc', language: 'Pennsylvania German' },
  { code: 'smn', language: 'Inari Sami' },
  { code: 'kaa', language: 'Karakalpak' },
  { code: 'szy', language: 'Sakizaya' },
  { code: 'arc', language: 'Aramaic' },
  { code: 'to', language: 'Tongan' },
  { code: 'nov', language: 'Novial' },
  { code: 'jam', language: 'Jamaican Patois' },
  { code: 'wo', language: 'Wolof' },
  { code: 'tpi', language: 'Tok Pisin' },
  { code: 'kbp', language: 'Kabiye' },
  { code: 'kbd', language: 'Kabardian Circassian' },
  { code: 'inh', language: 'Ingush' },
  { code: 'na', language: 'Nauruan' },
  { code: 'tet', language: 'Tetum' },
  { code: 'atj', language: 'Atikamekw' },
  { code: 'tcy', language: 'Tulu' },
  { code: 'ki', language: 'Kikuyu' },
  { code: 'ak', language: 'Akan' },
  { code: 'jbo', language: 'Lojban' },
  { code: 'bi', language: 'Bislama' },
  { code: 'roa-rup', language: 'Aromanian' },
  { code: 'lbe', language: 'Lak' },
  { code: 'kg', language: 'Kongo' },
  { code: 'lg', language: 'Luganda' },
  { code: 'ty', language: 'Tahitian' },
  { code: 'mdf', language: 'Moksha' },
  { code: 'xh', language: 'Xhosa' },
  { code: 'lld', language: 'Ladin' },
  { code: 'fj', language: 'Fijian' },
  { code: 'srn', language: 'Sranan' },
  { code: 'gcr', language: 'Guianan Creole' },
  { code: 'om', language: 'Oromo' },
  { code: 'ltg', language: 'Latgalian' },
  { code: 'sm', language: 'Samoan' },
  { code: 'chr', language: 'Cherokee' },
  { code: 'got', language: 'Gothic' },
  { code: 'kl', language: 'Greenlandic' },
  { code: 'pih', language: 'Norfolk' },
  { code: 'st', language: 'Sesotho' },
  { code: 'mnw', language: 'Mon' },
  { code: 'ny', language: 'Chichewa' },
  { code: 'nqo', language: 'N’Ko' },
  { code: 'cu', language: 'Old Church Slavonic' },
  { code: 'tw', language: 'Twi' },
  { code: 'tn', language: 'Tswana' },
  { code: 'ts', language: 'Tsonga' },
  { code: 'rmy', language: 'Romani' },
  { code: 'bm', language: 'Bambara' },
  { code: 'chy', language: 'Cheyenne' },
  { code: 'rn', language: 'Kirundi' },
  { code: 'tum', language: 'Tumbuka' },
  { code: 'ss', language: 'Swati' },
  { code: 'ch', language: 'Chamorro' },
  { code: 'ks', language: 'Kashmiri' },
  { code: 'iu', language: 'Inuktitut' },
  { code: 'pnt', language: 'Pontic' },
  { code: 'ady', language: 'Adyghe' },
  { code: 've', language: 'Venda' },
  { code: 'ee', language: 'Ewe' },
  { code: 'ik', language: 'Inupiak' },
  { code: 'ff', language: 'Fula' },
  { code: 'sg', language: 'Sango' },
  { code: 'din', language: 'Dinka' },
  { code: 'dz', language: 'Dzongkha' },
  { code: 'ti', language: 'Tigrinya' },
  { code: 'cr', language: 'Cree' },
  { code: 'mad', language: 'Madurese' },
  { code: 'nia', language: 'Nias' },
  { code: 'tay', language: 'Tayal' },
  { code: 'trv', language: 'Seediq' },
  { code: 'mni', language: 'Meitei' },
  { code: 'alt', language: 'Southern Altai' },
  { code: 'skr', language: 'Saraiki' },
  { code: 'dag', language: 'Dagbani' },
  { code: 'shi', language: 'Tachelhit' },
  { code: 'guw', language: 'Gun' },
];
